### ISSUE TITLE
There was a problem in displaying the Optic app. when clicked on the detail of difference on page diff 

### ISSUE THREAD

**Issue by huzairuje** [opticdev/optic#895] opened 2021-06-17 00:47 UTC
![image](https://user-images.githubusercontent.com/4037159/122312657-dd245580-cf3e-11eb-8ed3-c1ce4c86f788.png)
when click on the detail of difference on page diff 
![image](https://user-images.githubusercontent.com/4037159/122312745-1230a800-cf3f-11eb-9c1c-09319e1e96f8.png)
this loom recording is provided https://www.loom.com/share/8c4bee3390fe494db819d3cf69a0062d

There was a problem in displaying the Optic app.
Something that we didn't anticipate happened, and we can't recover from it automatically.
Please feel free to contact us about it.

Meanwhile, you could try the following:

    Create a debug file and email it to our team or open a GitHub issue:
        share a debug capture api debug:capture

in your browser.
Try a different browser, if you can.

**Comment by LouManglass** [comment] 2021-06-17 13:38
Hi @huzairuje,

I'm sorry to hear that! Would you be willing to share your capture session, which would include the traffic you sent to this example API and the spec you had built so far? You can attach it to this GitHub Issue or send it to us by email if you prefer. To do so, please run:

`api debug:capture <captureId>`

where CaptureId is the UUID-style section of the path at the top, circled in the screenshot attached:
![Screen Shot 2021-06-17 at 9 33 56 AM](https://user-images.githubusercontent.com/241059/122407029-51ff8b80-cf4f-11eb-8984-491f43d2b451.png)

If not, sharing a link to a repository with a sample project and traffic that reproduces the issue would be really helpful so we can dig into this further.

Thanks!

**Comment by huzairuje** [comment] 2021-06-18 15:16
oh hi @LouManglass , okay this repository should be helpful with the .optic. and before taht thank you for replying 
`https://github.com/huzairuje/go-echo-example`
and this repository 
`https://github.com/huzairuje/nestjs-typescript-mongodb-example`

**Comment by LouManglass** [comment] 2021-06-18 16:31
Hi @huzairuje ,

I cloned and set up  https://github.com/huzairuje/go-echo-example with a postgres database running in docker. I can run the project and see the existing documentation. I was able to reproduce a UI crash with a GET request to `/products/2` (which throws an error from the server, 500 response because that's not a UUID). It's not clear to me if that's the traffic you send to generate the issue in the first place.

Would you please send an example of the request bodies you sent for 

- GET /products/:products_id
- POST /products

in your Loom, so I can confirm I'm tracking down the correct issue?

**Comment by LouManglass** [comment] 2021-06-18 20:50
I've been tracking down this issue today and have a suspect. I've done some quick testing to work around the issue, and it looks like we've identified how to trigger it. I don't have a code fix yet, and I expect to have good news on that front Monday. If you have specific request bodies/procedures to generate this traffic you can send, I'll make sure I'm fixing the correct issue.

**Comment by LouManglass** [comment] 2021-06-21 22:39
Hi @huzairuje 

I have great news! The latest version of our Optic CLI, 10.0.6, is available on NPM as of now. You can update with:
npm install --global --legacy-peer-deps @useoptic/cli

The latest version resolves an issue in our capture process, which caused the diffs to break. You will need to remove all of the previous captures (delete the contents of the .optic/captures/ folder) and generate new traffic. Your specification is stored separately, and won't be affected. 

Let me know how this works out for you. Thanks for the feedback!

**Comment by LouManglass** [comment] 2021-06-23 15:32
Issue is resolved, no further reports, closing.

**Closed by LouManglass** 2021-06-23 15:32 UTC
Labels: resolved
