### ISSUE TITLE
Support for websocket passthrough

### ISSUE THREAD

**Issue by dyc3** [opticdev/optic#545] opened 2021-02-03 02:34 UTC
I'm working on a project that has an API and also accepts websocket connections. Currently, the websocket connections don't get passed through and the console output gets spammed with
```
Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at Socket.socketOnEnd (_http_client.js:459:23)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}
```

**Comment by acunniffe** [comment] 2021-02-03 12:57
Hey @dyc3 I followed up on Discord. If you're interested in fixing it yourself, here are some places to look and instructions on getting the repo running. If it's quicker to provide a reproducible example we can work off of, please upload one here: 

here's where I'd look
https://github.com/opticdev/optic/blob/develop/workspaces/cli-shared/src/httptoolkit-capturing-proxy.ts

we use a debugging proxy called mockttp under the hood
https://github.com/httptoolkit/mockttp

developer setup instructions for the optic repo (let me know if you need help)
https://github.com/opticdev/optic/blob/develop/Developer-setup.md

Seems like this will help quite a few users so I'm around to help you get this all fixed

**Comment by acunniffe** [comment] 2021-02-03 12:58
And just for my curiosity -- your API serves both Rest endpoints and WebSockets?

**Comment by dyc3** [comment] 2021-02-03 14:29
That's correct, through the same express server. This is the repo I'm working with, for reference: https://github.com/dyc3/opentogethertube

**Comment by acunniffe** [comment] 2021-02-03 17:46
Makes sense, I'll be pulling this tonight and taking a look. If you find any more out today lmk here or on discord. I'll circle back with my own learnings

**Comment by acunniffe** [comment] 2021-02-04 02:12
Hey @dyc3  -- looks like an issue within Mockttp  -- I was able to reproduce it with a simpler setup 
https://github.com/acunniffe/repo-socket-issue

Chatting now with the maintainers and seeing if there's anything obvious they want us to try.

**Comment by acunniffe** [comment] 2021-02-04 14:53
@dyc3  -- there's a fix underway in mockttp, I'll track it here and share it back when it's ready -- hopefully, we can get it incorporated and tested within the next few days. Want to make sure it gets a solid QA pass since it touches the proxy

**Comment by acunniffe** [comment] 2021-02-04 20:25
@dyc3  -- we got some changes through at mockttp: [See working version](https://www.loom.com/share/688e7737352f4d3aa19cf376ea9cec3d)

big thanks to @pimterry [made the required changes](https://github.com/httptoolkit/mockttp/commits?author=pimterry)

we'll have a PR out in the Optic repo after mockttp releases these updates.

**Comment by acunniffe** [comment] 2021-02-05 14:38
^ PR open https://github.com/opticdev/optic/pull/560

**Comment by acunniffe** [comment] 2021-02-05 18:47
9.0.8 fixes this. closing issue @dyc3 -- give it a run

**Closed by acunniffe** 2021-02-05 18:47 UTC
