### ISSUE TITLE
[optic 2.0.5] Fail to install.

### ISSUE THREAD

**Issue by anhnhoktvn** [opticdev/optic#6] opened 2018-11-01 04:10 UTC
Steps to reproduce:
1. run `npm install optic-cli -g`
2. run `optic`
Got the error:

```
? Finish Install: Configure local Optic server. Yes
Installing local Optic server...
downloading and preparing JRE + Optic Server [====================================] 100% 0.0s
Optic server could not be installed.Smoketest failed.
```

**Comment by acunniffe** [comment] 2018-11-01 21:29
@anhnhoktvn sorry about that. We've been working through environment specific bugs with the new CLI installer most of today. 

Can you share your operating system, os version, node version and npm version? I'll spin up a vm and try to reproduce.

**Comment by anhnhoktvn** [comment] 2018-11-02 05:49
I'm using 
Linux Mint 18.1
node v8.12.0
npm@6.4.1

**Comment by acunniffe** [comment] 2018-11-03 23:18
@anhnhoktvn I ran a docker image with all these versions. I could get the server to install, but it didn't seem to have access to it the next time the process ran. It seems like a permissions issue. 

To further help can you run the install again and then share the `ls` for `/usr/lib/node_modules/optic-cli/lib/jre`? 

Also can you check to see if a directory called `$HOME/.optic-storage` was created? 

Will get to the bottom of this, thanks for your help

**Comment by anhnhoktvn** [comment] 2018-11-04 11:40
Here are some infomation.
I have changed the default npm installation folder to avoid permission issue.
I also have a jdk version in my machine, do I still need another one?

```
~ $ ls ~/.pnpm-global/lib/node_modules/optic-cli/lib/jre/
jre  jre-install.js
```
```
~ $ ls ~/.optic-storage/
0c83f57c786a0b4a39efab23731c7ebc  c4755f318c6fdb260c47f26d0a24f0ca
a0f848942ce863cf53c0fa6cc684007d
```
```
~ $ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by acunniffe** [comment] 2018-11-04 18:01
This illuminates the problem for me — thank you. We pack a JRE of our own to reduce the surface area for issues. For some reason it’s downloading, but not saving in the right location — might have to do with the non-standard path. 

Let me play around with this some more over the next 24 and I’ll get back to you with a fix ASAP. 

We could probably add a flag to use a JRE that’s already installed on the machine, but that’s more of a feature request. They only weigh around 60mb so it doesn’t seem worth investing time in at this stage and I suspect it’s come with it’s set of challenges.

**Comment by acunniffe** [comment] 2018-11-05 14:56
@anhnhoktvn I spun up a dev environment on Mint and was able to debug the rest of the problems. You should have no issues getting it installed and running.

To save you time here's a cleanup command and the new install command. 
```
rm -rf ~/.optic-storage && sudo npm uninstall optic-cli -g
sudo npm install optic-cli@2.0.7 -g
```

The one issue I couldn't fix in the allotted time was getting the Optic IDE plugins to install on Linux automatically. I opened an [issue here](https://github.com/opticdev/optic-plugin-installer/issues/1) and would appreciate any thoughts you have on solving the problem. 

Cheers & have a great start to your week

**Comment by anhnhoktvn** [comment] 2018-11-05 15:50
Still not work :(
```
~ $ optic 
Welcome to Optic 2.0.7
? Please enter your email:  ***@gmail.com
? Finish Install: Configure local Optic server and install IDE plugins Yes
Installing local Optic server...
downloading and preparing JRE + Optic Server [====================================] 100% 0.0s
Optic server could not be installed.Smoketest failed.
```

**Comment by acunniffe** [comment] 2018-11-05 17:02
Hmm. So I'm running the same version of everything as you and it's working on this end. Must be something about your environment that I need to account for with installer code. 

Can you try running `sudo optic force-first-time`? I wonder if it has to do w/ permissions. 

and `optic start` in case it's just the Smoketest not working for some reason.

**Comment by anhnhoktvn** [comment] 2018-11-06 14:35
`sudo` does not work.
maybe it's something related to permission. Could you try installing it without sudo command?
```
sudo: optic: command not found
~ $ optic force-first-time
Welcome to Optic 2.0.7
? Please enter your email:  anhnhoktvn@gmail.com
? Finish Install: Configure local Optic server and install IDE plugins Yes
Installing local Optic server...
downloading and preparing JRE + Optic Server [====================================] 100% 0.0s
Optic server could not be installed.Smoketest failed.
```

**Comment by acunniffe** [comment] 2018-11-06 16:06
That would make the most sense. I just wiped my machine and installed it on a fresh VM
Linux Mint 18.1
node v8.12.0
npm@6.4.1

I can't get any node packages to install globally unless I use `sudo`. Not sure if this is expected behavior for Linux...
You mentioned changing your node_modules directory? Mind sharing the permissions on that, the optic-cli package and those optic directories in `~` ?

**Comment by anhnhoktvn** [comment] 2018-11-07 03:36
You can follow this instruction to install global packages without sudo:
[https://docs.npmjs.com/getting-started/fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

**Comment by acunniffe** [comment] 2018-11-12 18:37
@anhnhoktvn sorry it took me a few days to get to this, but I can confirm that after following your instructions I can reproduce. 

Seems small -- will get a fix up before switching to any other tasks.

**Comment by acunniffe** [comment] 2018-11-12 19:34
@anhnhoktvn Got it working on `optic-cli@2.0.9` 

We were relying on [node-app-root-path](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) to figure out where our package was running from, but it behaves incorrectly on Linux if you change your node-prefix. Everything should be using '__dirname' with relative paths now. 

I didn't do that originally because it makes refactoring a little uglier, I'd much rather be able reference all the jar files relative to the app root vs relative to the current file, but that clearly complicates this...

**Closed by acunniffe** 2018-11-12 19:34 UTC
